"""
Phase 5 — Pillar 3: Scientific Hypothesis Generator.

Generates testable scientific hypotheses from:
  - Causal mechanisms discovered by Pillar 2
  - Knowledge graph associations (Pillar 1)
  - Twin population data (Phase 4 VirtualPopulation)
  - Novel associations not captured by standard biomarkers

Each hypothesis includes:
  - Title and narrative description
  - Proposed mechanism with evidence
  - Confidence estimate
  - Validation plan (what to test, how, metrics)
"""

import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple, Any, Callable
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


# ── Data Types ────────────────────────────────────────────────

@dataclass
class HypothesisEvidence:
    """Evidence supporting a hypothesis."""
    source: str                # "causal_discovery", "literature", "twin_data", "knowledge_graph"
    description: str
    effect_size: float = 0.0
    confidence: float = 0.0
    p_value: float = 1.0
    n_observations: int = 0

    def __str__(self) -> str:
        return f"[{self.source}] {self.description} (β={self.effect_size:.3f}, p={self.p_value:.3f})"


@dataclass
class ValidationPlan:
    """Concrete plan to validate a hypothesis."""
    study_type: str              # "cohort_study", "randomized_trial", "in_silico", "experimental"
    population_description: str
    sample_size_estimate: int = 0
    primary_outcome: str = ""
    secondary_outcomes: List[str] = field(default_factory=list)
    duration_days: int = 0
    statistical_power: float = 0.0
    expected_effect_size: float = 0.0
    confounders_to_control: List[str] = field(default_factory=list)
    biomarkers_to_measure: List[str] = field(default_factory=list)

    def describe(self) -> str:
        return (
            f"{self.study_type} in {self.population_description} "
            f"(n={self.sample_size_estimate}, {self.duration_days}d, "
            f"power={self.statistical_power:.0%})"
        )


@dataclass
class ScientificHypothesis:
    """
    A complete, testable scientific hypothesis.

    Generated by the platform, reviewable by human scientists.
    """
    title: str
    summary: str
    proposed_mechanism: str
    evidence: List[HypothesisEvidence] = field(default_factory=list)
    overall_confidence: float = 0.0
    novelty_score: float = 0.0       # how novel vs established knowledge
    potential_impact: float = 0.0    # potential clinical/scientific impact
    validation_plan: Optional[ValidationPlan] = None
    generated_by: str = "hypothesis_generator"
    generated_at: float = 0.0
    tags: List[str] = field(default_factory=list)
    status: str = "generated"        # generated, reviewed, validated, rejected

    def __post_init__(self):
        if self.generated_at == 0.0:
            self.generated_at = __import__('time').time()

    def describe(self) -> str:
        return (
            f"**{self.title}**\n"
            f"*Confidence: {self.overall_confidence:.0%} | "
            f"Novelty: {self.novelty_score:.0%} | "
            f"Impact: {self.potential_impact:.0%}*\n"
            f"{self.summary}\n"
            f"Mechanism: {self.proposed_mechanism}\n"
            f"Evidence: {len(self.evidence)} sources\n"
            + (f"Validation: {self.validation_plan.describe()}"
               if self.validation_plan else "")
        )


# ── Hypothesis Templates (Domain Knowledge) ───────────────────

HYPOTHESIS_TEMPLATES = {
    "novel_biomarker": {
        "template": (
            "{biomarker} is a novel early predictor of {outcome} "
            "that outperforms standard biomarkers {standard_biomarkers} "
            "in {population}."
        ),
        "mechanism_template": (
            "{biomarker} reflects {biological_process} dysregulation, "
            "which precedes {outcome} by {timeline}. "
            "Current biomarkers ({standard_biomarkers}) capture "
            "downstream effects and therefore detect {outcome} later."
        ),
    },
    "causal_pathway": {
        "template": (
            "{exposure} causes {outcome} through {mediator} mediation, "
            "independent of {confounders}."
        ),
        "mechanism_template": (
            "{exposure} activates {upstream_pathway}, which upregulates "
            "{mediator}. Elevated {mediator} directly impairs "
            "{downstream_process}, resulting in {outcome}. "
            "This pathway is independent of {confounders}."
        ),
    },
    "interaction_effect": {
        "template": (
            "The effect of {intervention} on {outcome} is modified by "
            "{modifier}, with {modifier_level} showing {magnitude} "
            "greater benefit."
        ),
        "mechanism_template": (
            "{modifier} modulates the {biological_pathway} pathway "
            "through which {intervention} acts. Individuals with "
            "{modifier_level} have {molecular_difference}, leading to "
            "enhanced {intervention} efficacy."
        ),
    },
    "counterfactual_discovery": {
        "template": (
            "In silico twin simulation predicts that {intervention} "
            "would be substantially more effective than {alternative} "
            "in {subpopulation}, despite similar baseline characteristics."
        ),
        "mechanism_template": (
            "Twin modeling reveals latent {latent_factor} differences "
            "between responders and non-responders, driven by "
            "{biological_mechanism}. Standard clinical assessment "
            "misses these differences."
        ),
    },
}


# ── Hypothesis Generator ─────────────────────────────────────

class HypothesisGenerator:
    """
    Generate scientific hypotheses from multi-modal twin data.

    Sources:
      - Causal discovery results (MechanismGraph)
      - Knowledge graph associations
      - Virtual population data (twin cohorts)
      - Temporal pattern analysis
      - Outlier/novel association detection
    """

    def __init__(self, knowledge_graph: Optional[Any] = None):
        self.knowledge_graph = knowledge_graph
        self._hypotheses: List[ScientificHypothesis] = []
        self._templates = HYPOTHESIS_TEMPLATES

    def from_causal_mechanism(
        self, mechanism: Any,
        population_context: Optional[str] = None,
    ) -> ScientificHypothesis:
        """Generate a hypothesis from a single causal mechanism."""
        cause = mechanism.cause.replace("_", " ")
        effect = mechanism.effect.replace("_", " ")

        evidence = HypothesisEvidence(
            source="causal_discovery",
            description=(
                f"{mechanism.method} identified a causal relationship "
                f"between {cause} and {effect}"
            ),
            effect_size=mechanism.effect_size,
            confidence=mechanism.confidence,
            p_value=mechanism.p_value,
        )

        if mechanism.mediators:
            mediators_str = ", ".join(mechanism.mediators)
            title = f"Causal Pathway: {cause} → {mediators_str} → {effect}"
            summary = (
                f"Changes in {cause} lead to changes in {effect} "
                f"through mediation by {mediators_str}. "
                f"The direct effect is {mechanism.effect_size:.2f} "
                f"(p={mechanism.p_value:.3f})."
            )
            mechanism_desc = (
                f"{cause} activates upstream signaling that modulates "
                f"{mediators_str}, which in turn regulates {effect}. "
                f"This represents a testable causal pathway."
            )
        else:
            title = f"Direct Causal Effect: {cause} → {effect}"
            summary = (
                f"{cause} has a direct causal effect on {effect} "
                f"(β={mechanism.effect_size:.2f}, p={mechanism.p_value:.3f})."
            )
            mechanism_desc = (
                f"Changes in {cause} directly propagate to {effect} "
                f"through biochemical or physiological coupling."
            )

        hypothesis = ScientificHypothesis(
            title=title,
            summary=summary,
            proposed_mechanism=mechanism_desc,
            evidence=[evidence],
            overall_confidence=mechanism.confidence,
            novelty_score=0.5,
            potential_impact=0.5,
            validation_plan=ValidationPlan(
                study_type="in_silico",
                population_description=population_context or "general population",
                sample_size_estimate=500,
                primary_outcome=effect,
                duration_days=90,
                statistical_power=0.8,
                expected_effect_size=abs(mechanism.effect_size),
            ),
            tags=["causal", "mechanism"],
        )
        self._hypotheses.append(hypothesis)
        return hypothesis

    def from_novel_association(
        self, data: pd.DataFrame,
        target_variable: str,
        candidate_predictors: Optional[List[str]] = None,
        min_novelty: float = 0.3,
    ) -> List[ScientificHypothesis]:
        """
        Discover novel associations from twin population data.

        Finds predictors of target_variable that are not well-established
        in the literature, using residual analysis and feature selection.
        """
        hypotheses = []
        vars = candidate_predictors or [c for c in data.columns if c != target_variable]
        arr = data.values
        target_idx = list(data.columns).index(target_variable)

        for pred in vars:
            pred_idx = list(data.columns).index(pred)
            X, y = arr[:, pred_idx], arr[:, target_idx]
            if np.std(X) < 1e-10:
                continue
            corr = np.corrcoef(X, y)[0, 1]

            if abs(corr) > 0.2:
                # Build hypothesis
                evidence = HypothesisEvidence(
                    source="twin_data",
                    description=(
                        f"Association between {pred} and {target_variable} "
                        f"in {len(data)} twin observations"
                    ),
                    effect_size=float(corr),
                    confidence=float(abs(corr)),
                    n_observations=len(data),
                )

                hypothesis = ScientificHypothesis(
                    title=f"Novel Association: {pred} predicts {target_variable}",
                    summary=(
                        f"{pred} shows a {corr:.2f} correlation with "
                        f"{target_variable} in population data. "
                        f"This may represent a novel biomarker or risk factor."
                    ),
                    proposed_mechanism=(
                        f"The mechanism linking {pred} to {target_variable} "
                        f"is not yet established. Potential pathways include "
                        f"shared upstream regulators or direct physiological coupling."
                    ),
                    evidence=[evidence],
                    overall_confidence=min(1.0, abs(corr)),
                    novelty_score=0.7,
                    potential_impact=0.6,
                    validation_plan=ValidationPlan(
                        study_type="cohort_study",
                        population_description="target population",
                        sample_size_estimate=2000,
                        primary_outcome=target_variable,
                        secondary_outcomes=[pred],
                        duration_days=365,
                        statistical_power=0.8,
                        expected_effect_size=abs(corr),
                    ),
                    tags=["novel_association", "discovery"],
                )
                hypotheses.append(hypothesis)

        self._hypotheses.extend(hypotheses)
        return hypotheses

    def from_knowledge_graph(
        self, kg: Any,
        source_type: str = "biomarker",
        target_type: str = "disease",
        min_confidence: float = 0.4,
    ) -> List[ScientificHypothesis]:
        """Generate hypotheses from knowledge graph paths."""
        hypotheses = []

        # Query for all paths between types
        sources = kg.get_nodes_by_type(source_type) if hasattr(kg, 'get_nodes_by_type') else []
        for source in sources:
            neighbors = kg.get_neighbors(source.id) if hasattr(kg, 'get_neighbors') else []
            for neighbor_id, edge in neighbors:
                neighbor = kg.get_node(neighbor_id) if hasattr(kg, 'get_node') else None
                if neighbor and neighbor.node_type == target_type:
                    evidence = HypothesisEvidence(
                        source="knowledge_graph",
                        description=(
                            f"Knowledge graph edge: {source.name} → {neighbor.name} "
                            f"(confidence={edge.confidence:.2f})"
                        ),
                        effect_size=edge.weight,
                        confidence=edge.confidence,
                    )
                    hypothesis = ScientificHypothesis(
                        title=f"Knowledge Graph Discovery: {source.name} → {neighbor.name}",
                        summary=(
                            f"The knowledge graph identifies a {edge.edge_type.value} "
                            f"relationship between {source.name} and {neighbor.name}. "
                            f"This association may represent a testable hypothesis."
                        ),
                        proposed_mechanism=(
                            "See knowledge graph path details. "
                            "Further mechanistic investigation is warranted."
                        ),
                        evidence=[evidence],
                        overall_confidence=edge.confidence,
                        novelty_score=0.4,
                        potential_impact=0.5,
                        validation_plan=ValidationPlan(
                            study_type="in_silico",
                            population_description="twin cohort",
                            sample_size_estimate=1000,
                            primary_outcome=neighbor.name,
                            duration_days=90,
                            statistical_power=0.8,
                        ),
                        tags=["knowledge_graph"],
                    )
                    hypotheses.append(hypothesis)

        self._hypotheses.extend(hypotheses)
        return hypotheses

    def rank_hypotheses(self, top_k: int = 10) -> List[ScientificHypothesis]:
        """
        Rank hypotheses by combined confidence + novelty + impact.

        Returns top-k most promising hypotheses.
        """
        scored = []
        for h in self._hypotheses:
            score = (
                0.4 * h.overall_confidence +
                0.3 * h.novelty_score +
                0.3 * h.potential_impact
            )
            scored.append((score, h))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [h for _, h in scored[:top_k]]

    def get_all_hypotheses(self) -> List[ScientificHypothesis]:
        return self._hypotheses

    def clear(self) -> None:
        self._hypotheses = []


# ── Convenience API ───────────────────────────────────────────

def generate_hypotheses_from_cohort(
    cohort_data: pd.DataFrame,
    target_outcome: str = "Diabetes",
    hypothesis_generator: Optional[HypothesisGenerator] = None,
    mechanism_graph: Optional[Any] = None,
) -> List[ScientificHypothesis]:
    """
    One-shot: generate hypotheses from a virtual cohort.

    Args:
        cohort_data: DataFrame of twin population data
        target_outcome: Target variable for prediction/discovery
        hypothesis_generator: Pre-configured generator (creates new if None)
        mechanism_graph: Pre-discovered causal mechanism graph

    Returns:
        Ranked list of ScientificHypothesis
    """
    gen = hypothesis_generator or HypothesisGenerator()

    # 1. Generate from causal mechanisms
    if mechanism_graph:
        for mechanism in mechanism_graph.get_top_mechanisms(20):
            gen.from_causal_mechanism(mechanism)

    # 2. Generate from novel associations
    gen.from_novel_association(
        cohort_data, target_outcome,
        candidate_predictors=[c for c in cohort_data.columns if c != target_outcome],
    )

    return gen.rank_hypotheses(top_k=10)
